# Generated by Django 2.0.3 on 2019-09-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20190921_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=66)),
                ('cnpj_cpf', models.CharField(max_length=19)),
                ('endereco', models.CharField(max_length=16)),
                ('cidade', models.CharField(max_length=40)),
                ('telefone', models.CharField(max_length=17)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
