# Generated by Django 2.0.3 on 2019-09-27 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=66, unique=True)),
                ('descricao', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen_produto', models.ImageField(blank=True, null=True, upload_to='produtos_photos')),
                ('empresa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='account.Account')),
            ],
        ),
    ]
