# Generated by Django 2.0 on 2019-09-26 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account'),
        ('anuncios', '0002_auto_20190925_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncios',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.Account'),
        ),
    ]
