# Generated by Django 2.0 on 2019-09-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_anuncios_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncios',
            name='empresa',
        ),
        migrations.AddField(
            model_name='anuncios',
            name='imagen_anuncio',
            field=models.ImageField(blank=True, null=True, upload_to='anuncios_photos'),
        ),
    ]
