# Generated by Django 2.0 on 2019-09-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=6, unique=True)),
                ('cnpj_cpf', models.CharField(max_length=13, unique=True)),
                ('endereco', models.CharField(max_length=16, null=True)),
                ('cidade', models.CharField(max_length=6, unique=True)),
                ('telefone', models.CharField(max_length=17)),
                ('email', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
