# Generated by Django 2.0 on 2019-09-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
