# Generated by Django 2.0 on 2019-09-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20190922_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=19, unique=True),
        ),
    ]
