# Generated by Django 2.0 on 2019-09-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20190922_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
